### ISSUE TITLE
Prefix global tags

### ISSUE THREAD

**Issue by Techassi** [olithissen/dgf-monitoring#1]
Hier wäre es sinnvoll die globalen Tags zu prefixen, da es sonst zu Kollisionen kommen kann, wenn man den Output in einem bereits bestehenden Monitoring Setup aufnimmt. Für die Zukunft wäre das zu empfehlen, da vermutlich nicht alle Contributors einen eigenen Container oder eine separate Telegraf-Instanz laufen lassen wollen / können.

`Ist`
```toml
[global_tags]
  user = "foo"
  lat = "1.23"
  lon = "4.56"
```

`Empfehlung`
```toml
[global_tags]
  dgf_user = "foo"
  dgf_lat = "1.23"
  dgf_lon = "4.56"
```

Um diese Anpassung vornehmen zu können muss das Montoring Server-seitig angepasst werden. Auch müssen andere Contributors das Setup (Container oder Config) anpassen. In der jetzigen Phase wird dies noch relativ einfach umzusetzen sein, da es laut Karte im Moment nur 2 Nutzer gibt.
